Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2021-11, with the labels that each got.

#402 Imprisonment conversion
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Characters/Characters.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Converter.cs
  ImperatorToCK3/Imperator/Characters/Character.cs
  ImperatorToCK3/Imperator/Characters/Characters.cs
  ImperatorToCK3/Outputter/CharacterOutputter.cs
  ImperatorToCK3/Outputter/CharactersOutputter.cs
  ImperatorToCK3/Outputter/TitlesOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#403 Remove title history entries past bookmark date
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/Titles/TitleHistory.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/CommonUtils/History.cs
  ImperatorToCK3/Imperator/Jobs/Governorship.cs
Labels: enhancement

#413 More CK3 ProvinceMappingsTests
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvinceMappingsTests.cs
  ImperatorToCK3.UnitTests/TestFiles/CK3_province_mappings_messy.txt
  ImperatorToCK3.UnitTests/TestFiles/CK3_province_mappings_messy2.txt
  ImperatorToCK3/CK3/Provinces/ProvinceMappings.cs
  ImperatorToCK3/CK3/World.cs
Labels: test

#414 Fix System.IO.IOException on save preprocessing
  ImperatorToCK3/Helpers/RakalyCaller.cs
Labels: fix

#417 Set employer for every unlanded character from Imperator
  ImperatorToCK3.UnitTests/Imperator/Characters/CharacterTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Characters/Characters.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Imperator/Characters/Character.cs
  ImperatorToCK3/Imperator/Characters/Characters.cs
  ImperatorToCK3/Outputter/CharacterOutputter.cs
Labels: enhancement

#421 Output landed titles' can_create and can_create_on_partition attributes
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
Labels: fix

#425 Refined Imperator Territory -> CK3 Holding mapping
  ImperatorToCK3/CK3/Provinces/Province.cs
Labels: enhancement

#443 Fix CoA output
  ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
Labels: fix

#444 Don't set employer for dead characters
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/Outputter/CharacterOutputter.cs
Labels: fix

#448 Add basic mapping for Huna culture from Simple Timeline Extender mod
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#449 Remove mapping to Teutonic Order
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/Data_Files/configurables/title_map.txt
Labels: fix

#450 Fix Imperator owner country not being set for provinces
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Imperator/Provinces/Province.cs
  ImperatorToCK3/Imperator/Provinces/ProvinceFactory.cs
Labels: fix

#452 Fix KeyNotFoundException on linking jailors
  ImperatorToCK3/CK3/Characters/Character.cs
Labels: fix
