Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2021-12, with the labels that each got.

#456 Make Nuragic culture's gfx same as Basque's
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/01_aboriginal.txt
Labels: enhancement

#458 Use country's religion and primary culture as a fallback for provinces
  ImperatorToCK3/CK3/Provinces/Province.cs
Labels: enhancement

#463 Fix broken history output on BC conversion date
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Converter.cs
  ImperatorToCK3/Imperator/Countries/CountryName.cs
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: fix

#465 A few tests for mappers
  ImperatorToCK3.UnitTests/Mappers/DeathReason/DeathReasonMapperTests.cs
  ImperatorToCK3.UnitTests/Mappers/Nickname/NicknameMapperTests.cs
  ImperatorToCK3.UnitTests/Mappers/Trait/TraitMapperTests.cs
  ImperatorToCK3/Mappers/CoA/CoaMapper.cs
  ImperatorToCK3/Mappers/DeathReason/DeathReasonMapper.cs
  ImperatorToCK3/Mappers/Nickname/NicknameMapper.cs
  ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
  ImperatorToCK3/Mappers/Trait/TraitMapper.cs
Labels: test

#466 RakalyCaller and AccessoryGeneData tests
  ImperatorToCK3.UnitTests/Helpers/RakalyCallerTests.cs
  ImperatorToCK3.UnitTests/Imperator/Characters/AccessoryGeneDataTests.cs
  ImperatorToCK3.UnitTests/ImperatorToCK3.UnitTests.csproj
  ImperatorToCK3/Helpers/RakalyCaller.cs
Labels: test

#471 Fix government change by country's current ruler being ignored
  ImperatorToCK3/CK3/Titles/Title.cs
Labels: fix

#479 Support mod CoAs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Mappers/CoA/CoaMapper.cs
Labels: enhancement

#486 Copy mods' colored emblems to generated CK3 mod
  ImperatorToCK3/Converter.cs
  ImperatorToCK3/Outputter/ColoredEmblemsOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#496 Create Linux release zip
  .github/workflows/create_release.yml
  ImperatorToCK3/Properties/PublishProfiles/linux-x64.pubxml
  build_linux.sh
Labels: enhancement

#493 Regional mappings to Armenian Apostolic, Coptic and Nestorian by @TinWiz
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
Labels: enhancement

#498 Use stable version of SixLabors.ImageSharp
  ImperatorToCK3.UnitTests/ImperatorToCK3.UnitTests.csproj
  ImperatorToCK3/ImperatorToCK3.csproj
  nuget.config
Labels: dependencies

#505 Improve cross platform reliability in ColoredEmblemsOutputter
  ImperatorToCK3/Outputter/ColoredEmblemsOutputter.cs
Labels: enhancement

#506 Improve cross-platform reliability in ImperatorRegionMapper
  .github/workflows/create_release.yml
  ImperatorToCK3/Mappers/Region/ImperatorRegionMapper.cs
Labels: enhancement

#507 Improve cross-platform reliability in CK3RegionMapper
  ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
Labels: enhancement
