Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2022-02, with the labels that each got.

#557 Fix succession laws not being converted
  ImperatorToCK3.UnitTests/Outputter/SuccessionTriggersOutputterTests.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/Outputter/SuccessionTriggersOutputter.cs
Labels: bug

#562 Make CK3 bookmark date default to save's current date if not set in options
  ImperatorToCK3/Configuration.cs
  ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml
  ImperatorToCK3/Imperator/World.cs
Labels: enhancement

#564 Convert governors under duchies to county holders
  ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
  ImperatorToCK3.UnitTests/Mappers/TagTitle/TagTitleMapperTests.cs
  ImperatorToCK3.UnitTests/TestFiles/LandedTitlesTests/CK3/provinces.txt
  ImperatorToCK3.UnitTests/TestFiles/LandedTitlesTests/Imperator/game/map_data/areas.txt
  ImperatorToCK3.UnitTests/TestFiles/LandedTitlesTests/Imperator/game/map_data/regions.txt
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Imperator/Jobs/Governorship.cs
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Mappers/CoA/CoaMapper.cs
  ImperatorToCK3/Mappers/Province/ProvinceMapper.cs
  ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs
  ImperatorToCK3/Mappers/Trait/TraitMapper.cs
  ImperatorToCK3/Outputter/BookmarkOutputter.cs
Labels: enhancement

#565 Support variables in culture mappings
  ImperatorToCK3.UnitTests/Mappers/Culture/CultureMapperTests.cs
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Mappers/Culture/CultureMappingRule.cs
Labels: enhancement

#569 Add imp_germanic_cultures variable to culture_map.txt for less duplication
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#577 Update CK3 region loading for CK3 1.5
  ImperatorToCK3.UnitTests/Mappers/Culture/CultureMappingTests.cs
  ImperatorToCK3.UnitTests/Mappers/Region/CK3RegionMapperTests.cs
  ImperatorToCK3.UnitTests/Mappers/Religion/ReligionMappingTests.cs
  ImperatorToCK3.UnitTests/TestFiles/CK3/game/map_data/geographical_regions/geographical_region.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/CorrectParentLocationsReported/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/CorrectParentLocationsReported/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LoadingBrokenCountyWillThrowException/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LoadingBrokenCountyWillThrowException/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LoadingBrokenDuchyWillThrowException/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LoadingBrokenDuchyWillThrowException/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LoadingBrokenRegionWillThrowException/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LoadingBrokenRegionWillThrowException/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationNameValidationWorks/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationNameValidationWorks/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesCorrectlyFail/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesCorrectlyFail/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesFailForNonsense/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesFailForNonsense/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesSucceedsForCountyField/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesSucceedsForCountyField/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesSucceedsForProvinceField/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesSucceedsForProvinceField/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesWork/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/LocationServicesWork/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/WrongParentLocationsReturnNull/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/WrongParentLocationsReturnNull/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/empty/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CK3RegionMapperTests/empty/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CultureMappingTests/MatchOnRegion/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CultureMappingTests/MatchOnRegion/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CultureMappingTests/MatchOnRegionFailsForWrongRegion/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CultureMappingTests/MatchOnRegionFailsForWrongRegion/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CultureMappingTests/empty/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/CultureMappingTests/empty/game/map_data/island_regions.txt
  ImperatorToCK3.UnitTests/TestFiles/regions/ReligionMappingTests/game/map_data/geographical_regions/regions.txt
  ImperatorToCK3/Data_Files/configurables/version.txt
  ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
Labels: enhancement

#596 Update province mappings for CK3 1.5
  ImperatorToCK3/Data_Files/configurables/province_mappings.txt
Labels: enhancement

#597 Add <culture>_prefix localization for all our cultures
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_cultures_l_english.yml
Labels: enhancement

#600 Limit Norse religion mapping to Scandinavia
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
Labels: enhancement

#634 2 traditions for each culture
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_aboriginal.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_anatolian.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_arvanite.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_berber_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_central_germanic_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_chaldean.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_east_germanic.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_east_slavic_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_gaulish.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_iranian_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_israelite_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_mongolic_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_punic.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_thracian.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_tyrrhenian.txt
Labels: enhancement

#637 Fix title history output for CK3 1.5
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/Titles/TitlesHistory.cs
Labels: fix

#638 Fixes for blankMod cultures
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_byzantine_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_chaldean.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_latin_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_north_germanic_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/pillars/IRToCK3_heritage.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/01_cultural_heritages_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/01_cultural_heritages_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/01_cultural_heritages_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/korean/01_cultural_heritages_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/01_cultural_heritages_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/01_cultural_heritages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/01_cultural_heritages_l_spanish.yml
Labels: fix

#644 Name equivalency fixes
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_equivalency/IR_names.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_equivalency/vanilla_override.txt
Labels: fix

#642 Replace CK3 owner with Imperator historical tag in CultureMapper
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/Imperator/Countries/CountryTests.cs
  ImperatorToCK3.UnitTests/Mappers/Culture/CultureMapperTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Provinces/Province.cs
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Imperator/Countries/Country.cs
  ImperatorToCK3/Imperator/Countries/CountryCollection.cs
  ImperatorToCK3/Imperator/Countries/CountryFactory.cs
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Mappers/Culture/CultureMapper.cs
  ImperatorToCK3/Mappers/Culture/CultureMappingRule.cs
Labels: enhancement

#646 Fix for amies breaking parsing of the save
  ImperatorToCK3/Imperator/World.cs
Labels: fix

#650 Map Magadhi culture to Bengali
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#654 Fix development from vanilla overriding converted one
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/World.cs
Labels: fix

#655 Remove duchies from mappings in `configurables/title_map.txt`
  ImperatorToCK3/Data_Files/configurables/title_map.txt
Labels: enhancement
