Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2022-09, with the labels that each got.

#930 Estimate marriages to start 300 days before child's birth
  ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
Labels: enhancement

#931 More reliable marriage date estimation
  ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
Labels: enhancement

#933 Fix character purging causing null references in CK3
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
Labels: fix

#937 Invictus Morocco mappings
  ImperatorToCK3/Data_Files/configurables/province_mappings.txt
Labels: enhancement

#939 Convert character attributes
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/Imperator/Characters/CharacterAttributes.cs
Labels: enhancement

#941 Determine CK3 character intrigue from I:R finesse
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
Labels: enhancement

#935 Initial support for selecting CK3 mods (see "CK3 mods" tab in the frontend)
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Configuration.cs
  ImperatorToCK3/Data_Files/fronter_configuration/fronter-configuration.txt
  ImperatorToCK3/Data_Files/fronter_configuration/zzz_frontend_override_l_english.yml
  ImperatorToCK3/Outputter/BookmarkOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#944 Determine CK3 character intrigue from I:R charisma and finesse
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
Labels: enhancement

#949 Blank mod compatch for CK3 1.7
  ImperatorToCK3/Data_Files/blankMod/output/common/customizable_localization/99_fr_custom_loc.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/on_action/game_start.txt
Labels: enhancement

#950 Bump target CK3 version to 1.7
  ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/Data_Files/configurables/version.txt
  ImperatorToCK3/Outputter/BookmarkOutputter.cs
  ImperatorToCK3/Resources/images/LatestReleaseBanner.png
  ImperatorToCK3/Resources/images/LatestReleaseBanner.xcf
Labels: enhancement

#952 Fix for imported I:R custom character names breaking localization syntax
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/Imperator/World.cs
Labels: fix

#953 Comment out references to CCU script values
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/pillars/00_language_venetic.txt
Labels: fix

#957 Lower log level of some warnings
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
  ImperatorToCK3/CK3/Provinces/ProvinceMappings.cs
Labels: enhancement

#958 Add optional `irCulture` parameter to government mappings
  ImperatorToCK3.UnitTests/CK3/Titles/RulerTermTests.cs
  ImperatorToCK3.UnitTests/Mappers/Government/GovernmentMapperTests.cs
  ImperatorToCK3.UnitTests/Mappers/Government/GovernmentMappingTests.cs
  ImperatorToCK3/CK3/Titles/RulerTerm.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/Data_Files/configurables/government_map.txt
  ImperatorToCK3/Mappers/Government/GovernmentMapper.cs
  ImperatorToCK3/Mappers/Government/GovernmentMapping.cs
Labels: enhancement

#959 Use Ubuntu runners to generate coverage reports
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: github_actions

#964 Add a workflow to check spelling
  .github/workflows/spelling.yml
Labels: github_actions

#967 Workflow tweaks
  .github/workflows/build.yml
  .github/workflows/build_dev_version.yml
  .github/workflows/create_release.yml
Labels: github_actions

#969 Handle more entries in CK3 province history
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvinceHistoryTests.cs
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvincesTests.cs
  ImperatorToCK3/CK3/Provinces/Province.cs
  ImperatorToCK3/CK3/Provinces/ProvinceHistory.cs
  ImperatorToCK3/CK3/Provinces/ProvinceMappings.cs
  ImperatorToCK3/CommonUtils/History.cs
Labels: enhancement

#971 Add `provinces_prehistory.txt` configurable to limit which CK3 special buildings are preserved in conversion
  ImperatorToCK3/CK3/Provinces/Province.cs
  ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Data_Files/configurables/characters_prehistory.txt
  ImperatorToCK3/Data_Files/configurables/provinces_prehistory.txt
  ImperatorToCK3/Imperator/World.cs
Labels: enhancement

#962 Use self-hosted runners in build workflow
  .github/workflows/build.yml
  .github/workflows/build_dev_version.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/create_release.yml
  .github/workflows/test.yml
Labels: github_actions

#981 Support Korean localization
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_cultures_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/noculture_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/CONVERTER_cultures_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/noculture_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/ir_names_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/noculture_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/korean/ir_names_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/korean/noculture_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/legacy/ir_character_names_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/noculture_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/noculture_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/noculture_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/noculture_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/noculture_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/noculture_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/noculture_l_spanish.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/ir_names_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/noculture_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/ir_names_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/noculture_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/ir_names_l_spanish.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/noculture_l_spanish.yml
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Outputter/LocalizationOutputter.cs
Labels: enhancement
