Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2022-08, with the labels that each got.

#844 Add GitHub workflow to detect braces mismatches
  .github/workflows/find_braces_mismatches.yml
Labels: github_actions

#827 Use ModFilesystem in CK3 ProvinceCollection
  ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvinceMappingsTests.cs
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvincesTests.cs
  ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
  ImperatorToCK3.UnitTests/TestFiles/CK3ProvinceMappingTests/leftEqualsRight/history/province_mapping/CK3_province_mappings_messy.txt
  ImperatorToCK3.UnitTests/TestFiles/CK3ProvinceMappingTests/normal/history/province_mapping/CK3_province_mappings.txt
  ImperatorToCK3.UnitTests/TestFiles/CK3ProvinceMappingTests/overwriting/history/province_mapping/CK3_province_mappings_messy2.txt
  ImperatorToCK3.UnitTests/TestFiles/CK3ProvincesTests/history/provinces/CK3ProvincesHistoryFile.txt
  ImperatorToCK3.UnitTests/TestFiles/CK3_province_mappings_messy.txt
  ImperatorToCK3.UnitTests/TestFiles/LandedTitlesTests/CK3/game/history/provinces/provinces.txt
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
  ImperatorToCK3/CK3/Provinces/ProvinceMappings.cs
  ImperatorToCK3/CK3/World.cs
Labels: enhancement

#855 Venetic culture improvements from https://steamcommunity.com/sharedfiles/filedetails/?id=2830456287
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_latin_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_lists/00_venetic.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/pillars/00_heritage_venetic.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/pillars/00_language_venetic.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/pillars/IRToCK3_language.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/traditions/venetic_culture_traditions.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/flavorization/venetic_title_holders.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/men_at_arms_types/venetic_maa_types.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_names_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/traditions/venetic_heritages_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/traditions/venetic_languages_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/venetic_cultures_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/venetic_maa_traditions_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/venetic_name_lists_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/venetic_realms_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/dynasties/dynasty_names_venetic_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/traditions/venetic_heritages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/traditions/venetic_languages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/traditions/venetic_traditions_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/venetic_cultures_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/venetic_maa_traditions_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/venetic_name_lists_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/venetic_realms_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/venetic_titles_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/dynasties/dynasty_names_venetic_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/configurables/cultural_title_names.txt
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Data_Files/converter_globals/ReadMe.txt
Labels: enhancement

#856 Fix some name_equivalency and culture GFX log errors
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_byzantine_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_gaulish.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_mongolic_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_equivalency/IR_names.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_equivalency/vanilla_override.txt
Labels: fix

#857 Fix "Negative value in add_gold" log errors
  ImperatorToCK3/Outputter/CharacterOutputter.cs
Labels: fix

#870 Progress logging
  ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
  ImperatorToCK3/CK3/Map/MapData.cs
  ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/Imperator/Provinces/ProvinceCollection.cs
  ImperatorToCK3/Imperator/Religions/ReligionCollection.cs
  ImperatorToCK3/Mappers/CoA/CoaMapper.cs
  ImperatorToCK3/Mappers/Culture/CultureMapper.cs
  ImperatorToCK3/Mappers/DeathReason/DeathReasonMapper.cs
  ImperatorToCK3/Mappers/Government/GovernmentMapper.cs
  ImperatorToCK3/Mappers/Nickname/NicknameMapper.cs
  ImperatorToCK3/Mappers/Province/ProvinceMapper.cs
  ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
  ImperatorToCK3/Mappers/Region/ImperatorRegionMapper.cs
  ImperatorToCK3/Mappers/Religion/ReligionMapper.cs
  ImperatorToCK3/Mappers/SuccessionLaw/SuccessionLawMapper.cs
  ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs
  ImperatorToCK3/Mappers/Trait/TraitMapper.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#871 Fix name loc for `pmpese` and `taliaite` creation names
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_culture_creation_names_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_cultures_l_english.yml
Labels: fix

#876 More progress logging
  ImperatorToCK3/CK3/Armies/MenAtArmsType.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Configuration.cs
  ImperatorToCK3/Imperator/Armies/UnitCollection.cs
  ImperatorToCK3/Imperator/Countries/CountryFactory.cs
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#878 Fix log4net config
  ImperatorToCK3/log4net.config
Labels: fix

#880 Fix some culture GFX log errors
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_central_germanic_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_chaldean.txt
Labels: fix

#881 Add more progress logging
  ImperatorToCK3/Imperator/Defines.cs
  ImperatorToCK3/Imperator/World.cs
Labels: enhancement

#882 Update of factors for holy site effect
  ImperatorToCK3/Data_Files/configurables/holy_site_effect_mappings.txt
Labels: fix

#883 Catch exceptions while reading I:R defines
  ImperatorToCK3/Imperator/Defines.cs
Labels: fix

#877 Output ruling dynasty CoAs
  ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
  ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
  ImperatorToCK3.UnitTests/Mappers/TagTitle/TagTitleMapperTests.cs
  ImperatorToCK3.UnitTests/Outputter/CoatOfArmsOutputterTests.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
  ImperatorToCK3/Outputter/ColoredEmblemsOutputter.cs
  ImperatorToCK3/Outputter/NamedColorsOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#886 Give Iceland to Papar if bookmark date is between 40 and 830
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvinceDetailsTests.cs
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvinceHistoryTests.cs
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvinceTests.cs
  ImperatorToCK3.UnitTests/CK3/Provinces/ProvincesTests.cs
  ImperatorToCK3.UnitTests/CK3/Religions/ReligionCollectionTests.cs
  ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
  ImperatorToCK3.UnitTests/CK3/Titles/RulerTermTests.cs
  ImperatorToCK3.UnitTests/CommonUtils/HistoryTests.cs
  ImperatorToCK3.UnitTests/Mappers/HolySiteEffect/HolySiteEffectMapperTests.cs
  ImperatorToCK3.UnitTests/Outputter/CoatOfArmsOutputterTests.cs
  ImperatorToCK3.UnitTests/Outputter/DynastiesOutputterTests.cs
  ImperatorToCK3.UnitTests/Outputter/ProvinceOutputterTests.cs
  ImperatorToCK3.UnitTests/Outputter/SuccessionTriggersOutputterTests.cs
  ImperatorToCK3.UnitTests/Outputter/TitlesOutputterTests.cs
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Provinces/Province.cs
  ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
  ImperatorToCK3/CK3/Provinces/ProvinceDetails.cs
  ImperatorToCK3/CK3/Provinces/ProvinceHistory.cs
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/TitleHistory.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/CommonUtils/DiffHistoryField.cs
  ImperatorToCK3/CommonUtils/History.cs
  ImperatorToCK3/CommonUtils/HistoryFactory.cs
  ImperatorToCK3/CommonUtils/IHistoryField.cs
  ImperatorToCK3/CommonUtils/SimpleFieldDef.cs
  ImperatorToCK3/CommonUtils/SimpleHistoryField.cs
  ImperatorToCK3/Data_Files/blankMod/output/common/governments/IRToCK3_governments.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_governments_l_english.yml
  ImperatorToCK3/ImperatorToCK3.csproj
  ImperatorToCK3/Outputter/BookmarkOutputter.cs
  ImperatorToCK3/Outputter/CharacterOutputter.cs
  ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
  ImperatorToCK3/Outputter/ProvinceOutputter.cs
Labels: enhancement

#888 Add missing culture mappings for Invictus
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#890 Fix some name equivalency errors from error.log
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_equivalency/IR_names.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_equivalency/vanilla_override.txt
Labels: fix

#889 Fix RakalyCaller.GetJson sometimes returning an empty string
  ImperatorToCK3.UnitTests/Helpers/RakalyCallerTests.cs
  ImperatorToCK3.UnitTests/Outputter/ProvinceOutputterTests.cs
  ImperatorToCK3/Helpers/RakalyCaller.cs
  ImperatorToCK3/Imperator/Defines.cs
Labels: fix

#892 Use custom_scotland as potential source for Icelandic Papar
  ImperatorToCK3/CK3/World.cs
Labels: enhancement

#893 Try to merge divided Imperator families
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
  ImperatorToCK3.UnitTests/Imperator/Families/FamilyTests.cs
  ImperatorToCK3.UnitTests/Outputter/DynastiesOutputterTests.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
  ImperatorToCK3/Imperator/Characters/Character.cs
  ImperatorToCK3/Imperator/Families/Family.cs
  ImperatorToCK3/Imperator/Families/FamilyCollection.cs
  ImperatorToCK3/Imperator/World.cs
Labels: enhancement

#900 Remove Newtonsoft.Json dependency
  ImperatorToCK3.UnitTests/Helpers/RakalyCallerTests.cs
  ImperatorToCK3/Imperator/Defines.cs
  ImperatorToCK3/ImperatorToCK3.csproj
Labels: enhancement

#901 Prevent two-way merging of families
  ImperatorToCK3/Imperator/Families/FamilyCollection.cs
Labels: fix

#902 Improve CK3 map data mod support
  ImperatorToCK3.UnitTests/CK3/Map/MapDataTests.cs
  ImperatorToCK3.UnitTests/CK3/Map/ProvinceDefinitionsTests.cs
  ImperatorToCK3/CK3/Map/MapData.cs
  ImperatorToCK3/CK3/Map/ProvinceDefinitions.cs
  ImperatorToCK3/CK3/World.cs
Labels: enhancement

#905 Expand Eremitic ruler generation to Faroe Islands
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Data_Files/blankMod/output/common/flavorization/CONVERTER_title_holders.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_title_names_l_english.yml
Labels: enhancement

#904 Make I:R civilization level to CK3 development ratio configurable
  ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Configuration.cs
  ImperatorToCK3/Data_Files/fronter_configuration/fronter-options.txt
  ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml
Labels: enhancement

#906 Improve I:R mods support
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
  ImperatorToCK3/Outputter/LocalizationOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#908 Fix exception when handling Iceland and Faroe Islands
  ImperatorToCK3/CK3/World.cs
Labels: fix

#909 Add mapping for `greco_indian` culture
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#910 Update files from @derekmark's Venetic Culture mod
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_lists/00_venetic.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/traditions/venetic_languages_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/venetic_name_lists_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/culture/venetic_realms_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/dynasties/dynasty_names_venetic_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/Ven_culture_events_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/Ven_deities_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/Ven_events_and_decisions_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/Ven_holy_sites_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/Ven_pagan_religion_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/culture/traditions/venetic_heritages_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/culture/traditions/venetic_languages_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/culture/venetic_cultures_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/culture/venetic_maa_traditions_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/culture/venetic_name_lists_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/culture/venetic_realms_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/culture/venetic_titles_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/dynasties/dynasty_names_venetian_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/dynasties/dynasty_names_venetic_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/from_venetic_mod/dynasties/personal_names_venetic_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/traditions/venetic_languages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/culture/venetic_name_lists_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/Ven_deities_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/Ven_events_and_decisions_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/Ven_holy_sites_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/Ven_pagan_religion_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/traditions/venetic_heritages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/traditions/venetic_languages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/traditions/venetic_traditions_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/venetic_cultures_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/venetic_maa_traditions_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/venetic_name_lists_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/venetic_realms_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/culture/venetic_titles_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/from_venetic_mod/dynasties/dynasty_names_venetic_l_simp_chinese.yml
Labels: enhancement

#912 Use male family form (e.g. Julius) instead of plural (e.g. Julii) for dynasty name if possible
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
  ImperatorToCK3.UnitTests/Outputter/DynastiesOutputterTests.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_lists/IRToCK3_zz_whatif.txt
  ImperatorToCK3/Imperator/Cultures/Culture.cs
  ImperatorToCK3/Imperator/Cultures/CultureGroup.cs
  ImperatorToCK3/Imperator/Cultures/CulturesDB.cs
  ImperatorToCK3/Imperator/Families/Family.cs
  ImperatorToCK3/Imperator/World.cs
Labels: enhancement

#916 Improve CK3 mod support in BookmarkOutputter
  ImperatorToCK3/Outputter/BookmarkOutputter.cs
Labels: enhancement

#917 Improve loc generation from PRY, SEL and MRY tags
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/Titles/Title.cs
Labels: enhancement

#915 Turn Salinatorian into a Roman divergence name
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/creation_names/IRToCK3_names.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_latin_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_cultures_l_english.yml
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#918 Use Royal Court mechanics instead of splitting Greek cultures on conversion
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/aesthetics_bundles/IRToCK3_aesthetics.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/creation_names/IRToCK3_names.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/creation_names/IRToCK3_names_hybrid.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_byzantine_new.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_gaulish.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_punic.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_thracian.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_aesthetics_bundles_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_cultures_l_english.yml
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#919 Relax the requirements for assigning de jure empires
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
Labels: enhancement

#920 Use I:R area and province names for governorship loc generation
  ImperatorToCK3.UnitTests/Mappers/Region/ImperatorAreaTests.cs
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/ImperatorToCK3.csproj
  ImperatorToCK3/Mappers/Region/ImperatorArea.cs
  ImperatorToCK3/Mappers/Region/ImperatorRegion.cs
  ImperatorToCK3/Mappers/Region/ImperatorRegionMapper.cs
Labels: enhancement

#926 Remove entries for Epirus,, which were conflicting with I:R setup, from prehistory.txt configurable
  ImperatorToCK3.sln.DotSettings
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Data_Files/configurables/prehistory.txt
Labels: fix
