Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2023-01, with the labels that each got.

#1138 Disable Rise of Islam by default until updated for CK3 1.8
  ImperatorToCK3/Data_Files/fronter_configuration/fronter-options.txt
  ImperatorToCK3/Data_Files/fronter_configuration/options_l_english.yml
Labels: enhancement

#1139 Map Neuric culture to Proto-Slavic
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#1140 Give West Germanic heritage to Suebi
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/cultures/IRToCK3_west_germanic_override.txt
Labels: fix

#1146 Default to black when loading a title with missing named color
  ImperatorToCK3/CK3/Titles/Title.cs
Labels: fix

#1150 Don't break conversion on importing I:R war with missing targeted state
  ImperatorToCK3/CK3/Provinces/Province.cs
  ImperatorToCK3/CK3/Wars/War.cs
  ImperatorToCK3/Program.cs
Labels: fix

#1154 Convert holding owners to barony holders
  ImperatorToCK3.UnitTests/Imperator/Countries/CountryTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Imperator/Countries/Country.cs
  ImperatorToCK3/Imperator/Countries/CountryFactory.cs
  ImperatorToCK3/Imperator/Provinces/Province.cs
  ImperatorToCK3/Imperator/Provinces/ProvinceFactory.cs
Labels: enhancement

#1155 Don't import I:R holdings to CK3 provinces with "none" holding
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
Labels: fix

#1158 Add Russian localizations by Luka_Moscovite
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/01_culture_name_lists_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_cultures_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_pagan_religion_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/IRtoCK3_holy_sites_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/ir_welcome_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/new_eras_l_russian.yml
  ImperatorToCK3/Data_Files/converter_globals/ReadMe.txt
Labels: enhancement

#1160 Convert Aestian culture to Prussian by default
  ImperatorToCK3/Data_Files/blankMod/output/history/characters/hellothere.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_title_names_l_russian.yml
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#1163 Fix file conflict in Russian localization
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_holy_sites_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/IRtoCK3_holy_sites_prelocalized_l_russian.yml
Labels: fix

#1167 Localize `name_list_palaungic`
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_culture_name_lists_l_english.yml
Labels: fix

#1172 Update FAQ and license files
  ImperatorToCK3/Data_Files/converter_globals/FAQ.txt
  ImperatorToCK3/Data_Files/converter_globals/ReadMe.txt
  ImperatorToCK3/Data_Files/converter_globals/after_converting.txt
  ImperatorToCK3/Data_Files/converter_globals/license.txt
Labels: enhancement

#1174 Update Christianity religion mappings for recent Invictus version
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
Labels: enhancement

#1175 Add `historicalTag` parameter to religion_map.txt
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/Mappers/Culture/CultureMapperTests.cs
  ImperatorToCK3.UnitTests/Mappers/Religion/ReligionMapperTests.cs
  ImperatorToCK3.UnitTests/Mappers/Religion/ReligionMappingTests.cs
  ImperatorToCK3.UnitTests/TestFiles/CK3/game/common/religion/religions/test_religion.txt
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Provinces/Province.cs
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
  ImperatorToCK3/Mappers/Culture/CultureMappingRule.cs
  ImperatorToCK3/Mappers/Religion/ReligionMapper.cs
  ImperatorToCK3/Mappers/Religion/ReligionMapping.cs
  global.json
Labels: enhancement

#1177 Disable fail-fast in release upload matrix job
  .github/workflows/create_release.yml
Labels: github_actions

#1178 Use newer GitHub Action for uploading release assets
  .github/workflows/create_release.yml
Labels: github_actions

#1179 Use ubuntu-latest runners to create release
  .github/workflows/create_release.yml
  global.json
Labels: github_actions

#1184 Update FAQ.txt
  ImperatorToCK3/Data_Files/converter_globals/FAQ.txt
Labels: documentation

#1188 Map Christianity in country of Armenia to `armenian_apostolic`
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
Labels: enhancement

#1195 Use .NET SDK 7.0.102
  global.json
Labels: .NET

#1197 `Fix tooltip typo
  ImperatorToCK3/Data_Files/fronter_configuration/configuration_l_english.yml
Labels: fix
