Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2024-04, with the labels that each got.

#1865 Prevent errors in RGB color definitions from causing conversion failure
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/ImperatorToCK3.csproj
Labels: enhancement

#1868 Prevent missing religious head character from causing an exception
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
Labels: enhancement

#1878 Technology conversion configurable through configurables/inventions_to_innovations_map.txt
  ImperatorToCK3/CK3/Cultures/Culture.cs
  ImperatorToCK3/CK3/Cultures/CultureCollection.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Imperator/Countries/Country.cs
  ImperatorToCK3/Imperator/Countries/CountryFactory.cs
  ImperatorToCK3/Imperator/Inventions/InventionsDB.cs
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/ImperatorToCK3.csproj
  ImperatorToCK3/Mappers/Technology/InnovationBonus.cs
  ImperatorToCK3/Mappers/Technology/InnovationLink.cs
  ImperatorToCK3/Mappers/Technology/InnovationMapper.cs
  ImperatorToCK3/Outputter/CulturesOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#1882 Use macos-14 runners to ensure arm64 architecture
  .github/workflows/build.yml
  .github/workflows/create_release.yml
  .github/workflows/test.yml
  .github/workflows/validate_dds_files.yml
Labels: github_actions

#1884 Fix ArgumentOutOfRangeException while generating title adjective
  ImperatorToCK3/CK3/Titles/Title.cs
Labels: fix

#1862 Add mappings from Inventions to Innovations (towards #163)
  ImperatorToCK3/Data_Files/configurables/inventions_to_innovations_map.txt
Labels: enhancement

#1888 Prevent exception when checking active inventions for country
  ImperatorToCK3/Imperator/Inventions/InventionsDB.cs
Labels: fix

#1890 Don't warn about pirates, rebels and mercenaries having no primary culture
  ImperatorToCK3/CK3/Cultures/CultureCollection.cs
Labels: fix

#1891 Fix syntax error in configurables/inventions_to_innovations_map.txt
  ImperatorToCK3/Data_Files/configurables/inventions_to_innovations_map.txt
Labels: fix

#1892 Fix portrait modifiers being added to characters after their death
  ImperatorToCK3/Outputter/CharactersOutputter.cs
Labels: fix

#1893 Map a few I:R inventions to CK3 innovations
  ImperatorToCK3/CK3/Cultures/CultureCollection.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Data_Files/configurables/inventions_to_innovations_map.txt
  ImperatorToCK3/Mappers/Technology/InnovationMapper.cs
Labels: enhancement

#1894 Prevent exception when grouping kingdoms into contiguous groups
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
Labels: fix

#1895 Purge unneeded dynasties
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
  ImperatorToCK3/CK3/World.cs
Labels: enhancement

#1896 Update PGCG.commonItems to 12.0.2
  ImperatorToCK3/ImperatorToCK3.csproj
Labels: dependencies

#1897 Add mapping for conquer_wargoal_2 from FMO mod
  ImperatorToCK3/Data_Files/configurables/wargoal_mappings.txt
Labels: enhancement

#1899 Don't use I:R sea provinces when converting character's religion
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
  ImperatorToCK3.UnitTests/Imperator/Characters/CharacterTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CommonUtils/Map/MapData.cs
  ImperatorToCK3/Imperator/Characters/Character.cs
Labels: enhancement

#1902 Log a user-friendly message when Rakaly is blocked by an antivirus
  ImperatorToCK3/Helpers/RakalyCaller.cs
Labels: enhancement

#1905 Fix for TFE compatibility: load innovations from CK3 and remove invalid technology mappings
  ImperatorToCK3/CK3/Cultures/CultureCollection.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Mappers/Technology/InnovationBonus.cs
  ImperatorToCK3/Mappers/Technology/InnovationLink.cs
  ImperatorToCK3/Mappers/Technology/InnovationMapper.cs
Labels: fix

#1910 Log a warning when an innovation bonus mapping has no I:R entries
  ImperatorToCK3.UnitTests/Mappers/Technology/InnovationBonusTests.cs
  ImperatorToCK3.UnitTests/Mappers/Technology/InnovationLinkTests.cs
  ImperatorToCK3/Mappers/Technology/InnovationBonus.cs
  ImperatorToCK3/Mappers/Technology/InnovationLink.cs
Labels: enhancement

#1911 Tweaks and fixes for characters purge
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Characters/CharactersLoader.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/CommonUtils/History.cs
  ImperatorToCK3/CommonUtils/LiteralHistoryField.cs
Labels: fix

#1912 Add missing description for Nhialacism
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/wap_religion_dinka_l_english.yml
Labels: fix

#1913 Blank out vanilla CK3 portrait modifiers file for historical characters
  ImperatorToCK3/Outputter/CharactersOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: fix

#1914 Remove duplicate loc for dynn_Makapagal
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/sea_dynasties_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/sea_dynasties_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/sea_dynasties_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/sea_dynasties_l_russian.yml
Labels: fix

#1918 Remove duplicate loc for dynn_Gatchalian
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/sea_dynasties_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/sea_dynasties_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/sea_dynasties_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/sea_dynasties_l_russian.yml
Labels: fix
