Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2025-09, with the labels that each got.

#2698 Fix exception due to concurrent collection update
  ImperatorToCK3/CK3/Characters/Character.cs
Labels: fix

#2701 Update for CK3 1.17, neo_minoan innovations fix, Invictus patches
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Data_Files/blankMod/output/common/culture/name_lists/IRToCK3_anatolian.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/on_action/cretan_to_neo_minoan_game_start.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/CONVERTER_languages_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/ir_names_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/CONVERTER_languages_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/ir_names_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/korean/CONVERTER_languages_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/korean/ir_names_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_vanilla_override_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/CONVERTER_languages_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/CONVERTER_languages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/CONVERTER_languages_l_spanish.yml
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
  ImperatorToCK3/Data_Files/configurables/converter_faiths.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_language.txt
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_languages_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/base/english/ir_names_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/base/russian/ir_names_l_russian.yml
  ImperatorToCK3/Data_Files/configurables/localization/base/simp_chinese/ir_names_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/configurables/localization/base/spanish/ir_names_l_spanish.yml
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks.txt
  ImperatorToCK3/Data_Files/configurables/title_map.txt
  ImperatorToCK3/Data_Files/configurables/version.txt
Labels: enhancement

#2724 Reduce the complexity of a few methods
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/World.cs
Labels: maintenance

#2725 Unit tests for the DoctrineCategory class
  ImperatorToCK3.UnitTests/CK3/Religions/DoctrineCategoryTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Religions/Religion.cs
  ImperatorToCK3/CommonUtils/EnumerableExtensions.cs
  ImperatorToCK3/ImperatorToCK3.csproj
Labels: test

#2726 Improve code coverage
  .vscode/tasks.json
  ImperatorToCK3.UnitTests/CK3/Religions/FaithTests.cs
  ImperatorToCK3.UnitTests/CK3/Religions/HolySiteTests.cs
  ImperatorToCK3.UnitTests/CK3/Religions/ReligionTests.cs
  ImperatorToCK3/CK3/Religions/Faith.cs
  ImperatorToCK3/CK3/Religions/Religion.cs
Labels: test

#2727 Minor optimizations
  ImperatorToCK3.UnitTests/CK3/Characters/CK3CharacterTests.cs
  ImperatorToCK3.UnitTests/CK3/Dynasties/DynastyTests.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
  ImperatorToCK3/Imperator/Inventions/InventionsDB.cs
  ImperatorToCK3/Mappers/Gene/MorphGeneTemplateMapper.cs
  ImperatorToCK3/Mappers/Technology/InnovationMapper.cs
  ImperatorToCK3/Outputter/BookmarkOutputter.cs
Labels: maintenance

#2728 Fix some problems found by ck3-tiger
  .github/workflows/integration_tests.yml
  ImperatorToCK3/Data_Files/configurables/ck3_characters_to_preserve.txt
Labels: fix

#2732 Fix some missing religious localization for the Burmic religion
  ImperatorToCK3/Data_Files/configurables/localization/base/english/sea_religion_burmic_l_english.yml
Labels: fix

#2734 Automatically remove duplicates in religion and faith localizations
  .github/workflows/integration_tests.yml
  ImperatorToCK3.UnitTests/CK3/Religions/ReligionTests.cs
  ImperatorToCK3/CK3/Religions/Faith.cs
  ImperatorToCK3/CK3/Religions/FaithData.cs
  ImperatorToCK3/CK3/Religions/Religion.cs
Labels: enhancement

#2736 Update removable_file_blocks_tfe.txt for latest TFE version
  .github/workflows/ck3-tiger.conf
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_tfe.txt
  ImperatorToCK3/Outputter/FileTweaker.cs
Labels: enhancement

#2737 TFE: prevent cultures from being in the Iron Age era at bookmark date
  ImperatorToCK3/CK3/Cultures/Culture.cs
  ImperatorToCK3/Outputter/CulturesOutputter.cs
Labels: fix

#2739 Improve the verification of CK3 Mod Directory
  ImperatorToCK3.UnitTests/ConfigurationTests.cs
  ImperatorToCK3/Configuration.cs
Labels: enhancement

#2740 Fix development for CK3 bookmark dates other than the save's date
  ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
  ImperatorToCK3.UnitTests/CK3/Titles/TitleTests.cs
  ImperatorToCK3.UnitTests/CommonUtils/IHistoryFieldTests.cs
  ImperatorToCK3.UnitTests/Imperator/Families/FamilyTests.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CommonUtils/IHistoryField.cs
  ImperatorToCK3/Outputter/TitlesOutputter.cs
Labels: fix

#2741 Fix some problems found by ck3-tiger
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks.txt
Labels: fix
