Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2025-01, with the labels that each got.

#2390 Add two traditions to Hellenistic culture
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
Labels: enhancement

#2393 Add the Imperial Tagmata tradition to the Hellenistic culture
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
Labels: enhancement

#2394 Prevent the Bosporan Kingdom formation through decision if it has a holder or de jure land
  .gitignore
  ImperatorToCK3/Data_Files/blankMod/output/common/decisions/zz_vanilla_decisions_override.txt
Labels: fix

#2397 Fix exception if the `special_headgear_blindfold` gene is not found
  ImperatorToCK3/CK3/Characters/DNAFactory.cs
Labels: fix

#2399 Invention mappings for The Fallen Eagle mod and improved compatibility for its 'After the Pharaohs' update
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Characters/CharactersLoader.cs
  ImperatorToCK3/CK3/Cultures/CultureCollection.cs
  ImperatorToCK3/CK3/Provinces/ProvinceCollection.cs
  ImperatorToCK3/CK3/Religions/Faith.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/CommonUtils/IHistoryField.cs
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Data_Files/configurables/inventions_to_innovations_map.liquid
  ImperatorToCK3/Data_Files/configurables/inventions_to_innovations_map.txt
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_tfe.txt
  ImperatorToCK3/Mappers/Technology/InnovationMapper.cs
  ImperatorToCK3/Mappers/Trait/TraitMapper.cs
Labels: enhancement

#2406 Fix a lot of errors reported by ck3-tiger for vanilla CK3 conversions
  ImperatorToCK3/Data_Files/configurables/ck3_characters_to_preserve.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks.txt
Labels: fix

#2407 Don't build Updater for the development build
  .github/workflows/build_dev_version.yml
Labels: github_actions

#2409 Handle DNA generation exceptions
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
Labels: fix

#2415 Compatch for Invictus 1.9.0.2
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
Labels: enhancement

#2423 Countless fixes to TFE conversion but apparently not enough to fix the crashes
  ImperatorToCK3.UnitTests/CommonUtils/HistoryTests.cs
  ImperatorToCK3.UnitTests/TestFiles/LandedTitlesTests/CK3/game/common/landed_titles/extra_landed_titles.txt
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Characters/CharactersLoader.cs
  ImperatorToCK3/CK3/Characters/DNAFactory.cs
  ImperatorToCK3/CK3/Cultures/CultureCollection.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Dynasties/DynastyCollection.cs
  ImperatorToCK3/CK3/Religions/DoctrineCategory.cs
  ImperatorToCK3/CK3/Religions/Faith.cs
  ImperatorToCK3/CK3/Religions/HolySite.cs
  ImperatorToCK3/CK3/Religions/Religion.cs
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/Titles/TitleRankUtils.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/CommonUtils/EnumerableExtensions.cs
  ImperatorToCK3/CommonUtils/Genes/AccessoryGeneTemplate.cs
  ImperatorToCK3/CommonUtils/Genes/WeightBlock.cs
  ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_tfe_override_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_vanilla_override_l_english.yml
  ImperatorToCK3/Data_Files/configurables/ck3_characters_to_preserve.txt
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
  ImperatorToCK3/Data_Files/configurables/dynasties_to_preserve.txt
  ImperatorToCK3/Data_Files/configurables/dynasty_houses_to_preserve.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_tfe.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_tfe.txt
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Outputter/CharactersOutputter.cs
  ImperatorToCK3/Outputter/FileTweaker.cs
  ImperatorToCK3/Outputter/OnActionOutputter.cs
  ImperatorToCK3/Outputter/PillarOutputter.cs
  ImperatorToCK3/Outputter/ReligionsOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: fix

#2426 Vanilla conversion localization fixes and some debug logging
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/ir_deities_l_english.yml
  ImperatorToCK3/Data_Files/configurables/converter_faiths.txt
  ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_religions_l_english.yml
  ImperatorToCK3/Mappers/Region/CK3RegionMapper.cs
Labels: fix

#2439 Fix the Faroe Islands remaining Catholic after the conversion
  ImperatorToCK3/CK3/World.cs
Labels: fix

#2451 Rename Ancient Egyptian to Kemetic and Egyptian to Misri
  ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_vanilla_override_l_english.yml
Labels: enhancement

#2455 Fix random Christian characters being generated in AEP
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_aep.txt
Labels: fix

#2460 Updated province mappings for Asia Expansion Project version 0.8.2
  ImperatorToCK3/Data_Files/configurables/province_mappings/terra_indomita_to_aep.txt
Labels: enhancement

#2461 Fix the logic for handling invalid duchy capitals
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
Labels: fix

#2462 Fix a big part of AEP Indonesia having one culture and faith
  ImperatorToCK3/Data_Files/configurables/province_mappings/terra_indomita_to_aep.txt
Labels: fix

#2463 Fix most of the converter's religions not having a pilgrimage doctrine
  ImperatorToCK3/CK3/Religions/Faith.cs
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
  ImperatorToCK3/Data_Files/configurables/converter_faiths.txt
Labels: fix

#2440 Add Gelonian, Qin, Neo Minoan and Cretan cultures
  ImperatorToCK3/Data_Files/blankMod/output/common/on_action/cretan_to_neo_minoan_game_start.txt
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_cultures_l_english.yml
Labels: enhancement

#2467 Add a name-based country mapping to e_byzantium
  .github/workflows/build.yml
  ImperatorToCK3.UnitTests/Mappers/TagTitle/TagTitleMapperTests.cs
  ImperatorToCK3.UnitTests/Mappers/TagTitle/TitleMappingTests.cs
  ImperatorToCK3/Data_Files/configurables/title_map.txt
  ImperatorToCK3/Imperator/Countries/Country.cs
  ImperatorToCK3/Imperator/Countries/CountryFactory.cs
  ImperatorToCK3/Imperator/Countries/CountryName.cs
  ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs
  ImperatorToCK3/Mappers/TagTitle/TitleMapping.cs
Labels: enhancement

#2469 Minor fixes for The Fallen Eagle conversions, but apparently not enough to fix the crashes
  ImperatorToCK3/Data_Files/blankMod/output/localization/french/01_cultural_heritages_l_french.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/german/01_cultural_heritages_l_german.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/korean/01_cultural_heritages_l_korean.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/russian/01_cultural_heritages_l_russian.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/simp_chinese/01_cultural_heritages_l_simp_chinese.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/spanish/01_cultural_heritages_l_spanish.yml
  ImperatorToCK3/Data_Files/configurables/ccu_heritage_parameters.txt
  ImperatorToCK3/Data_Files/configurables/ccu_language_parameters.txt
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/00_language_venetic.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_heritage.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_language.txt
  ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_cultural_heritages_l_english.yml
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_tfe.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_tfe.txt
Labels: fix

#2470 Fix for the Qin culture using an invalid ethnicity
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
Labels: fix

#2472 Tweaks for conversion to WtWSMS version 0.1.6
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_language.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_wtwsms.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_wtwsms.txt
  ImperatorToCK3/Outputter/FileTweaker.cs
Labels: enhancement

#2477 Update for TFE's 2025-01-27 hotfix
  ImperatorToCK3/CK3/Characters/CharactersLoader.cs
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_tfe.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_tfe.txt
Labels: enhancement
