Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2025-04, with the labels that each got.

#2545 Prefer `administrative_government` over TFE's `imperial_government`
  ImperatorToCK3/Data_Files/configurables/government_map.txt
Labels: enhancement

#2555 Bump PGCG.commonItems to 15.1.7
  ImperatorToCK3/ImperatorToCK3.csproj
Labels: dependencies

#2565 Treat an empty save as a user error
  ImperatorToCK3/Imperator/World.cs
Labels: enhancement

#2562 Fixes for the determining of governorships' goverments
  ImperatorToCK3.UnitTests/CK3/Characters/CharacterCollectionTests.cs
  ImperatorToCK3.UnitTests/CK3/Titles/LandedTitlesTests.cs
  ImperatorToCK3.UnitTests/CK3/Titles/RulerTermTests.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/RulerTerm.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/Data_Files/configurables/government_map.txt
Labels: fix

#2570 Don't warn about undefined CoA when dynamic CoA extraction is skipped
  ImperatorToCK3.UnitTests/Mappers/Coa/CoaMapperTests.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/Mappers/CoA/CoaMapper.cs
Labels: enhancement

#2571 Avoid localization key hash conflicts when generating CK3 title IDs
  ImperatorToCK3.UnitTests/Mappers/TagTitle/TagTitleMapperTests.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/Mappers/TagTitle/TagTitleMapper.cs
Labels: fix

#2572 Compatch for WtWSMS 0.1.6.1
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_heritage.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_wtwsms.txt
Labels: enhancement

#2575 Performance tweaks and cleanup
  ImperatorToCK3.UnitTests/TestHelpers/TestCK3LocDB.cs
  ImperatorToCK3/CK3/CK3LocDB.cs
  ImperatorToCK3/CK3/Characters/Character.cs
  ImperatorToCK3/CK3/Characters/CharacterCollection.cs
  ImperatorToCK3/CK3/Characters/DNAFactory.cs
  ImperatorToCK3/CK3/Cultures/CultureCollection.cs
  ImperatorToCK3/CK3/Dynasties/Dynasty.cs
  ImperatorToCK3/CK3/Provinces/Province.cs
  ImperatorToCK3/CK3/Religions/Faith.cs
  ImperatorToCK3/CK3/Religions/Religion.cs
  ImperatorToCK3/CK3/Religions/ReligionCollection.cs
  ImperatorToCK3/CK3/Titles/LandedTitles.cs
  ImperatorToCK3/CK3/Titles/Title.cs
  ImperatorToCK3/CK3/Wars/War.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/CommonUtils/EnumerableExtensions.cs
  ImperatorToCK3/CommonUtils/Map/ProvinceDefinition.cs
  ImperatorToCK3/Configuration.cs
  ImperatorToCK3/Imperator/Characters/Character.cs
  ImperatorToCK3/Imperator/Countries/CountryName.cs
  ImperatorToCK3/Imperator/Cultures/Culture.cs
  ImperatorToCK3/Imperator/Families/FamilyCollection.cs
  ImperatorToCK3/Imperator/Religions/ReligionCollection.cs
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Mappers/Culture/CultureMappingRule.cs
  ImperatorToCK3/Mappers/DeathReason/DeathReasonMapper.cs
  ImperatorToCK3/Mappers/Nickname/NicknameMapper.cs
  ImperatorToCK3/Mappers/Province/ProvinceMappingsVersion.cs
  ImperatorToCK3/Mappers/TagTitle/TitleMapping.cs
  ImperatorToCK3/Mappers/Technology/InnovationMapper.cs
  ImperatorToCK3/Outputter/BookmarkOutputter.cs
  ImperatorToCK3/Outputter/CoatOfArmsOutputter.cs
  ImperatorToCK3/Outputter/CulturesOutputter.cs
  ImperatorToCK3/Outputter/MenAtArmsOutputter.cs
Labels: enhancement

#2573 Various Edits (Cultures, WRE Title, TFE law fix, etc.)
  ImperatorToCK3/Data_Files/blankMod/output/common/coat_of_arms/coat_of_arms/99_attributed_arms.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/landed_titles/irtock3_titles.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/on_action/IRToCK3_admin_game_start.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/trigger_localization/IRToCK3_trigger_loc.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_vanilla_override_l_english.yml
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_cultures_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/base/english/CONVERTER_decisions_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/tfe/english/irtock3_tfe_misc_loc_l_english.yml
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_tfe.txt
  ImperatorToCK3/Data_Files/configurables/title_map.txt
Labels: enhancement

#2576 Remove the `color2` attribute from landed title definitions
  ImperatorToCK3/Data_Files/blankMod/output/common/landed_titles/irtock3_titles.txt
  ImperatorToCK3/Data_Files/configurables/static_landed_titles.txt
Labels: fix
