Repository ParadoxGameConverters/ImperatorToCK3, pull requests merged in 2025-06, with the labels that each got.

#2627 Tweaks to the province outputting code
  .github/config/changelog-config.json
  ImperatorToCK3/Outputter/ProvincesOutputter.cs
Labels: maintenance

#2631 Conversion of Imperator Defensive Leagues + compatches for TFE and RoA
  ImperatorToCK3.UnitTests/Imperator/Diplomacy/DiplomacyDBTests.cs
  ImperatorToCK3/CK3/Cultures/PillarCollection.cs
  ImperatorToCK3/CK3/Diplomacy/DiplomacyDB.cs
  ImperatorToCK3/CK3/World.cs
  ImperatorToCK3/Data_Files/blankMod/output/common/on_action/IRToCK3_titles_game_start.txt
  ImperatorToCK3/Data_Files/blankMod/output/common/scripted_effects/irtock3_scripted_effects.txt
  ImperatorToCK3/Data_Files/blankMod/output/events/welcome.txt
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_events_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/english/CONVERTER_game_rules_l_english.yml
  ImperatorToCK3/Data_Files/blankMod/output/localization/replace/english/zzz_IRToCK3_mod_override_l_english.yml.liquid
  ImperatorToCK3/Data_Files/configurables/ccu_heritage_parameters.txt
  ImperatorToCK3/Data_Files/configurables/ccu_language_parameters.txt
  ImperatorToCK3/Data_Files/configurables/converter_cultures.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/00_heritage_venetic.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/00_language_venetic.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_heritage.txt
  ImperatorToCK3/Data_Files/configurables/cultural_pillars/IRToCK3_language.txt
  ImperatorToCK3/Data_Files/configurables/culture_map.txt
  ImperatorToCK3/Data_Files/configurables/localization/roa/english/ccu_heritage_parameters_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/roa/english/ccu_language_parameters_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/tfe/english/ccu_heritage_parameters_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/wtwsms/english/ccu_heritage_parameters_l_english.yml
  ImperatorToCK3/Data_Files/configurables/localization/wtwsms/english/ccu_language_parameters_l_english.yml
  ImperatorToCK3/Data_Files/configurables/province_mappings/imperator_invictus.txt
  ImperatorToCK3/Data_Files/configurables/province_mappings/terra_indomita_to_rajas_of_asia.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_roa.txt
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_tfe.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_roa.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_tfe.txt
  ImperatorToCK3/Data_Files/configurables/title_map.txt
  ImperatorToCK3/Imperator/Diplomacy/DiplomacyDB.cs
  ImperatorToCK3/Imperator/World.cs
  ImperatorToCK3/Outputter/CulturesOutputter.cs
  ImperatorToCK3/Outputter/DiplomacyOutputter.cs
  ImperatorToCK3/Outputter/WorldOutputter.cs
Labels: enhancement

#2643 Disable CETCompat in project settings
  ImperatorToCK3/ImperatorToCK3.csproj
Labels: maintenance

#2644 Prefer Chalcedonian over Orthodox and Catholic for TFE and WtWSMS
  ImperatorToCK3/CK3/Diplomacy/DiplomacyDB.cs
  ImperatorToCK3/Data_Files/configurables/religion_map.txt
Labels: fix

#2647 ROA Update
  ImperatorToCK3/Data_Files/blankMod/output/map_data/geographical_regions/zzz_IRToCK3_regions.txt.liquid
  ImperatorToCK3/Data_Files/configurables/removable_file_blocks_roa.txt
  ImperatorToCK3/Data_Files/configurables/replaceable_file_blocks_roa.txt
Labels: enhancement
